### ISSUE TITLE
Can it be translated into Chinese?

### ISSUE THREAD

**Issue by BahelanBaishan** [darwin-morocho/flutter-meedu#10]

**Comment by BahelanBaishan** [comment]
translate meedu.app content into chinese?

**Comment by darwin-morocho** [comment]
Hi @AceCodeE. Do you mean translate the meedu.app courses to chinese or add chinese documentation of flutter_meedu?

**Comment by AceCodeE** [comment]
add chinese documentation of flutter_meedu

**Comment by BahelanBaishan** [comment]
> Hi @AceCodeE. Do you mean translate the meedu.app courses to chinese or add chinese documentation of flutter_meedu? 

add chinese documentation of flutter_meedu

**Comment by darwin-morocho** [comment]
> > Hi @AceCodeE. Do you mean translate the meedu.app courses to chinese or add chinese documentation of flutter_meedu?
> 
> add chinese documentation of flutter_meedu

@AceCodeE if you can pass me the translated md files I can add its to the oficial docs or feel free make a PR. I can to create a new branch with all docs files ready to be transtaled to chinese

**Comment by darwin-morocho** [comment]
closed by no user response
