### ISSUE TITLE
Consumer and ConsumerWidget not defined

### ISSUE THREAD

**Issue by UNIcodeX** [darwin-morocho/flutter-meedu#11]
When trying to use `Consumer` and `ConsumerWidget` I get `Classes can only extend other classes. Try specifying a different superclass, or removing the extends clause.dart[extends_non_class](https://dart.dev/diagnostics/extends_non_class)`

**Comment by darwin-morocho** [comment]
> When trying to use `Consumer` and `ConsumerWidget` I get `Classes can only extend other classes. Try specifying a different superclass, or removing the extends clause.dart[extends_non_class](https://dart.dev/diagnostics/extends_non_class)`

Hi @UNIcodeX  witch version of dart are you using?

Also please add a screenshot where you are getting the warning

**Comment by UNIcodeX** [comment]
Hi. Thanks for the quick reply. I was moving too fast and only added the `meedu` package and not the `flutter_meedu` package. This is entirely my bad. 

Thanks again. 😓

**Comment by UNIcodeX** [comment]
Great package by the way! loving it. I don't like the style of some of the other state managers and I had picked up GetX, but it is apparently highly stigmatized for various reasons and allegedly not coded well, so I am grateful for this library. 🙏🏽
