### ISSUE TITLE
Problema con la librería modal_bottom_sheet

### ISSUE THREAD

**Issue by caospi** [darwin-morocho/flutter-meedu#14]
Hola @darwin-morocho estaba utilizando la librería modal_bottom_sheet y al navegar a una nueva vista con `Navigator.push` y `MaterialWithModalsPageRoute` ya que es necesario para que el modal se abra estilo iOS, luego de abrir el modal y volverlo a cerrar el consumer no vuelve a escuchar los cambios, te comparto un video [https://drive.google.com/file/d/1YCCITagTHaFd7iKxCtVKlxOeIkhkZRg3/view?usp=sharing](video) y el código fuente donde se replica:
[https://github.com/Carl0395/modal_test](url)
Cualquier duda que tengas, estoy a disposición 👍🏼

**Comment by darwin-morocho** [comment]
@Carl0395  gracias por tu reporte el bug ha sido solventado en la versión 8.2.0

**Comment by caospi** [comment]
@darwin-morocho Excelente muchas gracias por la pronta respuesta y solución 💯 🚀
