### ISSUE TITLE
A TestController was used after being disposed.

### ISSUE THREAD

**Issue by caospi** [darwin-morocho/flutter-meedu#2]
Hola @darwin-morocho estaba haciendo pruebas de navegación con SimpleController y al quitar varias vistas del stack a la vez, se genera esta excepción:

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A TestController was used after being disposed.
'package:meedu/src/state_managment/base_controller.dart':
Failed assertion: line 24 pos 12: '_listeners != null'
```

Pasa específicamente utilizando el SimpleBuilder en una de las vistas que quito del stack
te comparto un proyecto de prueba por si lo quieres replicar
https://github.com/Carl0395/TestFlutterMeedu.git

**Comment by darwin-morocho** [comment]
> https://github.com/Carl0395/TestFlutterMeedu.git

Saludos @Carl0395 gracias por el feedback y el ejemplo para reproducir el error. Este error fue solucionado en la version `meedu: ^0.5.4`

**Comment by caospi** [comment]
Hola @darwin-morocho gracias por responder tan rápido y gracias por ayudar a solucionar, seguiré utilizando este excelente paquete!. Saludos.
