### ISSUE TITLE
Null Safety migration

### ISSUE THREAD

**Issue by ElegantCrab** [darwin-morocho/flutter-meedu#3]
Are there any plans to migrate this package to null safety down the line? I've been using it and I'm in love with it.

**Comment by darwin-morocho** [comment]
> Are there any plans to migrate this package to null safety down the line? I've been using it and I'm in love with it.

hi @ElegantCrab  I'am migrating this package to null safety. I will update it in this week.

**Comment by darwin-morocho** [comment]
Now this package support flutter 2 and null safety
