### ISSUE TITLE
Duplicar Widget

### ISSUE THREAD

**Issue by aldogdl** [darwin-morocho/flutter-meedu#5]
He creado un Widget por medio de un controlador y su respectiva template, lo he hecho con ProviderPage y SimpleController, pero no he podido individualizar dichos widget.
Me explico, en una pagina independiente necesito llamar a ese widget varias veces, pero al hacerlo, resulta que no son instancias diferentes, ya que al manipular uno los demás también se mueven la mismo tiempo.
Como hago para independizarlos, ya provee con un GlobalKey y sin éxito.
Hasta he enviado un identificador independiente por cada widget y tampoco.
Espero me explique, de antemano te felicito por este componente, muchas gracias por todo.

**Comment by darwin-morocho** [comment]
Saludos @aldogdl podrías agregar código para entender mejor el problema. Por otro lado lo que entiendo es que quieres crear varios  widgets del mismo tipo  que utilizan un simpleController pero que cada sea independiente. Para lograr eso puedes usar el parámetro tag que sea único del widget provider o también sobreescribir el get tag en un Provider page. Luego para recuperar tu controller puedes usar **Get.i.find<TuController>(tag:'my-tag-unico')**

**Comment by aldogdl** [comment]
chispas!!! te agradezco mucho tu pronta respuesta, realmente no se como colocar todo el codigo que he elaborado, voy hacer todo lo posible por lograrlo ya que esto me interesa mucho.

Este es mi codigo del Widget:

`class InputBuscadorWidget extends ProviderPage<InputBuscadorController> {

  final String placeHolder;
  final String idUnico;
  final List<Map<String, dynamic>> items;
  InputBuscadorWidget({@required this.idUnico, @required this.placeHolder, @required this.items});

  @override
  InputBuscadorController create(BuildContext context){
    InputBuscadorController controller = InputBuscadorController();
    controller.idUnico = this.idUnico;
    controller.placeHolder = placeHolder;
    return controller;
  }

  @override
  Widget buildPage(BuildContext context, InputBuscadorController controller) {

    return Column(
      children: [
        Row(
          children: [
            Expanded(
              flex: 6,
              child: TextButton.icon(
                style: ButtonStyle(
                  alignment: Alignment.centerLeft,
                  backgroundColor: MaterialStateProperty.resolveWith<Color>((_) => Colors.white),
                ),
                onPressed: () => _pageBuscador(controller),
                icon: Icon(Icons.arrow_drop_down, color: Colors.grey),
                label: SimpleBuilder<InputBuscadorController>(
                  id: 'placeholder_$idUnico',
                  builder: (_) {

                    print(':::::placeholder_$idUnico');

                    return Text(
                      controller.placeHolder,
                      textScaleFactor: 1,
                      textAlign: TextAlign.left,
                      style: TextStyle(
                        color: (controller.placeHolder == this.placeHolder) ? Colors.grey : Colors.black,
                        fontSize: 17,
                        letterSpacing: 1.1
                      ),
                    );
                  }
                )
              )
            ),
            Flexible(
              flex: 1,
              child: SizedBox(
                width: 50,
                child: TextButton.icon(
                  style: ButtonStyle(
                    alignment: Alignment.centerRight,
                    padding: MaterialStateProperty.resolveWith((_) => EdgeInsets.zero)
                  ),
                  onPressed: () => controller.placeHolder = this.placeHolder,
                  icon: Icon(Icons.close, size: 29, color: Colors.red),
                  label: Text('')
                )
              )
            )
          ]
        ),
        Divider()
      ],
    );
  }
  
  ///
  Future<void> _pageBuscador(InputBuscadorController controller) async {
    
    await ruta.push(
      InputBuscadorLstWidget(
        items: items,
        itemSelect: (Map<String, dynamic> resultSelect) => controller.updatePlaceHolder = resultSelect['nombre']
      ),
      backGestureEnabled: true,
      fullscreenDialog: true,
      transition: ruta.Transition.rightToLeft
    );
    
  }

}`


Este es el controlados:

`class InputBuscadorController extends SimpleController {

  String _placeHolder = '';
  String idUnico = '';

  get placeHolder => this._placeHolder;
  set placeHolder(String placeHolder) => this._placeHolder = placeHolder;
  set updatePlaceHolder(String placeHolder) {
    this._placeHolder = placeHolder;
    update(['placeholder_$idUnico']);
  }
}`

y para llamar a dichos Widget hago lo siguiente:

InputBuscadorWidget(
    idUnico: 'mrks',
    placeHolder: '* La Marca...',
    items: controller.marcas,
  );

InputBuscadorWidget(
    idUnico: 'anios',
    placeHolder: '* El Año es...',
    items: controller.anios,
  );

por medio de idUnico, hago que los id de cada SimpleBuilder sean diferentes.

**Comment by aldogdl** [comment]
hola amigo muy buenas noches, disculpa mi insistencia pero estoy preocupado por este problemilla, y quiero ser muy claro, la verdad es que no creo que sea un error en este complemento, mas bien yo he de estar haciendo algo mal.

Despues de probar y probar creo di con el problema mas no con la solución:

El problema esta en que llamo a estos widget dentro de un showModalBottomSheet de la siguiente manera:

`  ///
  void _cambiarDeAuto(BuildContext context, InvAltaPiezasController controller) async {

    await showModalBottomSheet(
      context: context,
      useRootNavigator: true,
      builder: (_) {

        return Column(children: [

          InputBuscadorWidget(
            idUnico: 'anio_uno',
            placeHolder: '* El Año es...',
            items: buildAnios(),
          ),
          InputBuscadorWidget(
            idUnico: 'anio_dos',
            placeHolder: '* El Año es...',
            items: buildAnios(),
          ),
          InputBuscadorWidget(
            idUnico: 'anio_tres',
            placeHolder: '* El Año es...',
            items: buildAnios(),
          ),
        ],);
      }
    );
  }`

Al parecer cada que hago una modificación a cualquier widget InputBuscadorWidget, se repinta el modal y es cuando se vuelve loco toda mi clase.

Por ahi voy,!!!1 jejeje pero todavía no llego.

**Comment by aldogdl** [comment]
Mi amigo, si quieres que tenga exito tu paquete que esta muy bueno, no nos abandones con respecto al apoyo que te solicitamos, por fa :-)

**Comment by darwin-morocho** [comment]
> Mi amigo, si quieres que tenga exito tu paquete que esta muy bueno, no nos abandones con respecto al apoyo que te solicitamos, por fa :-)

Hola @aldogdl  no siempre tendré el tiempo ra responder de forma inmediata. Por otro lado el código proporcionado no es suficiente para replicar el problema hay muchas partes faltantes y tambien veo algunas cosas que no termino de entender en el codigo

**Comment by darwin-morocho** [comment]
@aldogdl  adjunto un ejemplo básico de un diálogo con varios widgets del mismo tipo utilizando un tag

```dart
import 'package:flutter/material.dart';
import 'package:flutter_meedu/state.dart';
import 'package:meedu/get.dart';
import 'package:meedu/state.dart';

class ModalAndTagsExamplePage extends StatelessWidget {
  const ModalAndTagsExamplePage({Key? key}) : super(key: key);

  void _showDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (_) => Material(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CounterView(tag: "tag1"),
            CounterView(tag: "tag2"),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {
                Navigator.pop(context);
              },
              child: Text("CLOSE"),
            )
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: Text("Show dialog"),
          onPressed: () => _showDialog(context),
        ),
      ),
    );
  }
}

class CounterView extends StatelessWidget {
  final String tag;
  const CounterView({Key? key, required this.tag}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Provider<CounterController>(
      tag: this.tag,
      create: (_) => CounterController(),
      child: Container(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            SimpleBuilder<CounterController>(
              tag: this.tag,
              id: 'counter',
              builder: (_) => Text("${_.counter}"),
            ),
            SizedBox(width: 10),
            ElevatedButton(
              onPressed: () {
                final controller = Get.i.find<CounterController>(tag: this.tag);
                controller.increment();
              },
              child: Icon(Icons.add),
            )
          ],
        ),
      ),
    );
  }
}

class CounterController extends SimpleController {
  int _counter = 0;
  int get counter => _counter;

  void increment() {
    _counter++;
    update(['counter']);
  }
}
```

**Comment by aldogdl** [comment]
Mil gracias por tu respuesta la analizare de inmediato, no puedo implementar rápidamente esta solución ya que estoy utilizando el método de ProviderPage en todos mis widget, no estoy familiarizado con ese método que tu propones, pero te lo agradezco mucho de todos modos, mil gracias amigo, si tuvieras el tiempo y las ganas, crees que pudieras colocar el mismo ejemplo con el método ProviderPage, a fin de cuentas es más documentación que proporcionas para las futuras personas que usen tu complemento, 

Aun así felicidades, esta muy bien tu paquete flutter, lo recomiendo :-)
