### ISSUE TITLE
MultiProvider Missing on 4.3.0

### ISSUE THREAD

**Issue by ElegantCrab** [darwin-morocho/flutter-meedu#6]
I've been using this package and I love it but I'm still using the version 1.1.1 on one of my production ready apps.

However, when I upgraded to 4.3.0 , my multiprovider went missing. I don't have access to a multiprovider and I've been trying to look for another class which does the same but I can't find it.

Is it me or is the multiprovider missing on this latest version with nullsafety?

**Comment by darwin-morocho** [comment]
hi @ElegantCrab yes since  4.x.x versión multiprovider was removed due to the breaking changes of this package. You have the class ProviderListener to listen your provider I will add a new class like MultiProvider in the next days

**Comment by darwin-morocho** [comment]
@ElegantCrab  since `flutter_meedu:^4.4.0` you can use the `MultiProviderListener` widget.
for more info go to https://flutter.meedu.app/docs/4.x.x/state-managment/simple-notifier/#listen-the-changes-in-your-controller
