### ISSUE TITLE
Global form key duplicated

### ISSUE THREAD

**Issue by eossa** [darwin-morocho/flutter-meedu#9]
Hola Darwin, tengo un problema:

Estoy usando una global key para un formulario y la cree en el SimpleNotifier

```dart
class ExampleController extends SimpleNotifier {
...
  GlobalKey<FormState> formKey = GlobalKey<FormState>();
...
}
```

Entonces hago el siguiente flujo
VistaInicial -> VistaLista -> VistaModificarItem -> VistaAgregarItem

La VistaModificarItem y la VistaAgregarItem son la misma solo que cuando se agrega tiene un parámetro 0 y cuando se edita un parámetro distinto de 0.

El problema ocurre cuando intento pasar desde VistaModificarItem a VistaAgregarItem, o desde VistaAgregarItem a otra VistaAgregarItem.

Intenté usar router.popAndPushNamed('/create'), pero antes de que se llame el dispose arroja un error de que la GlobalKey está duplicada.

¿Qué podría hacer en ese caso?, ¿acaso indicar autoDispose: false y llamar el dispose antes del router.push?

**Comment by darwin-morocho** [comment]
parace que necesitas usar los tags https://flutter.meedu.app/docs/5.x.x/state-management/working-with-tags


cuando navdgas de una pantalla que usa un provider a otra que otiliza el mismo provider no importa si haces el pop de la primera pantalla ya que para que el provider sea destruido primero debe terminar la transición de pantalla. Otra cosa que puedes hacer es usar auto dispose false y a tus páginas convertirlas a un statefulwidget y sobreescribir el método dispose y ahí liberar el provider

**Comment by eossa** [comment]
Muchas gracias por la rápida respuesta, efectivamente con la tag solucioné el problema.
